steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gothic-span-362715/github.com/pav-le/cont-dev/$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gothic-span-362715/github.com/pav-le/cont-dev/$SHORT_SHA']
  
 
