steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gothic-span-362715/github.com/pav-le/cont-dev:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gothic-span-362715/github.com/pav-le/cont-dev:$SHORT_SHA']  
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy gothic-span-362715', '--region=europe-west1', '--platform=managed', '--image=gcr.io/gothic-span-362715/github.com/pav-le/cont-dev:$SHORT_SHA']
  
  

 
